name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: beerapp pipeline
        runs-on: ubuntu-latest
        timeout-minutes: 40
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '17.x'
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  mvnw clean verify
