name: Triage pull requests and issues
on:
  issues:
    types: opened
  pull_request:
    types: opened
jobs:
  apply-label:
    permissions:
      contents: read # for andymckay/labeler to determine modified files
      pull-requests: write # for andymckay/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "area: triage"
          ignore-if-labeled: true
